// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TILApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221129042539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Acronym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Long")
                        .HasColumnType("TEXT");

                    b.Property<string>("Short")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acronym");
                });
#pragma warning restore 612, 618
        }
    }
}
